### ISSUE TITLE
Missing Python Script and Default Data Pack; Request for Detailed Instructions on Modifying Villager Trades

### ISSUE THREAD

**Issue by juba7** [AverageAnime/create-engineers#4]
Hello,

Thank you for developing the Create: Engineers mod. I noticed that the Python script and default data pack mentioned in the wiki are not included in the mod package. Could you please provide these files or offer detailed guidance on how to modify villager trades?

Thank you for your assistance.

Best regards,

**Comment by AverageAnime** [comment]
Sorry about that. This will have everything you need.

https://github.com/AverageAnime/create-engineers/tree/master/tools

I will be making proper instructions at some point, so let me know if you still need help.
